### ISSUE TITLE
This repository is dead?

### ISSUE THREAD

**Issue by jonyw4** [cypress-io/snapshot#119]

**Comment by bahmutov** [comment]
This repository is not getting enough development time, I personally recommend using https://github.com/meinaart/cypress-plugin-snapshots

**Comment by jonyw4** [comment]
Alright thanks @bahmutov!

**Comment by reintroducing** [comment]
@bahmutov cypress-plugin-snapshots (and realistically all the snapshot plugins listed on the Cypress plugins page under Visual Tests not being third party services like Percy or Applitools) are basically dead. Is there any way to take just JSON snapshots like Jest has through Cypress that is currently recommended now that Cypress 10 is out or has there been no headway made into this by the official Cypress team?

**Comment by bahmutov** [comment]
I welcome maintainers to help out with those plugins
